packages: ['.']

allowBuilds:
  cpu-features: true
  esbuild: true
  protobufjs: true
  ssh2: true
  unrs-resolver: true
minimumReleaseAgeExclude:
  - '@ethersphere/bee-js@13.0.0'
  - '@ethersphere/core-sdk@0.1.1'
  - '@typescript-eslint/eslint-plugin@8.67.0'
  - '@typescript-eslint/parser@8.67.0'
  - '@typescript-eslint/project-service@8.67.0'
  - '@typescript-eslint/scope-manager@8.67.0'
  - '@typescript-eslint/tsconfig-utils@8.67.0'
  - '@typescript-eslint/type-utils@8.67.0'
  - '@typescript-eslint/types@8.67.0'
  - '@typescript-eslint/typescript-estree@8.67.0'
  - '@typescript-eslint/utils@8.67.0'
  - '@typescript-eslint/visitor-keys@8.67.0'
