export enum FileManagerEvents {
  FILE_UPLOADED = 'file-uploaded',
  FILE_UPDATED = 'file-updated',
  FILE_DOWNLOADED = 'file-downloaded',
  FILE_TRASHED = 'file-trashed',
  FILE_RECOVERED = 'file-recovered',
  FILE_FORGOTTEN = 'file-forgotten',
  FILE_VERSION_RESTORED = 'file-version-restored',
  FILE_MOVED = 'file-moved',
  INITIALIZED = 'initialized',
  DRIVE_CREATED = 'drive-created',
  DRIVE_FORGOTTEN = 'drive-forgotten',
  DRIVE_DESTROYED = 'drive-destroyed',
  FOLDER_FORGOTTEN = 'folder-forgotten',
  FOLDER_TRASHED = 'folder-trashed',
  FOLDER_RECOVERED = 'folder-recovered',
  FOLDER_CREATED = 'folder-created',
  FILES_UPLOADED = 'files-uploaded',
  STATE_INVALID = 'state-invalid',
}
