export enum FileManagerEvents {
  INITIALIZED = 'initialized',
  STATE_INVALID = 'state-invalid',
  FILE_UPLOADED = 'file-uploaded',
  FILE_UPDATED = 'file-updated',
  FILE_TRASHED = 'file-trashed',
  FILE_RECOVERED = 'file-recovered',
  FILE_FORGOTTEN = 'file-forgotten',
  FILE_VERSION_RESTORED = 'file-version-restored',
  FILE_MOVED = 'file-moved',
  FILES_UPLOADED = 'files-uploaded',
  FOLDER_MOVED = 'folder-moved',
  FOLDER_FORGOTTEN = 'folder-forgotten',
  FOLDER_TRASHED = 'folder-trashed',
  FOLDER_RECOVERED = 'folder-recovered',
  FOLDER_CREATED = 'folder-created',
  DRIVE_CREATED = 'drive-created',
  DRIVE_RENAMED = 'drive-renamed',
  DRIVE_UNRESOLVED = 'drive-unresolved',
  DRIVE_FORGOTTEN = 'drive-forgotten',
  TRASH_EMPTIED = 'trash-emptied',
}
